FROM node:6

RUN set -ex \
      && DEBIAN_FRONTEND=noninteractive \
      && apt-get update \
      && apt-get install -y --no-install-recommends apt-utils locales libcairo2-dev libjpeg62-turbo-dev libpango1.0-dev libgif-dev build-essential \
      && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
      && dpkg-reconfigure --frontend=noninteractive locales \
      && update-locale LANG=en_US.UTF-8
ENV LANG en_US.UTF-8

VOLUME /usr/src/app

WORKDIR /usr/src/app

EXPOSE 3055

# use docker attach and "Ctrl-p + Ctrl-q" in order to attach to, and gracefully detach from the container or use "Ctrl-c" in order to cancel the process (once attached)
CMD [ "bash" ]
